/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppGudangWilayahRouteImport } from './routes/_app.gudang-wilayah'
import { Route as AppMitraRouteImport } from './routes/_app.mitra'
import { Route as AppTsoRouteImport } from './routes/_app.tso'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAgenAgenIdRouteImport } from './routes/_app.agen.$agenId'
import { Route as AppOutletOutletIdRouteImport } from './routes/_app.outlet.$outletId'
import { Route as AppSalesAreaRegisterRouteImport } from './routes/_app.sales-area.register'
import { Route as AppTsoIndexRouteImport } from './routes/_app.tso.index'
import { Route as AppTsoTsoIdRouteImport } from './routes/_app.tso.$tsoId'
import { Route as AppTsoCreateRouteImport } from './routes/_app.tso.create'
import { Route as AppAgenAgenIdIndexRouteImport } from './routes/_app.agen.$agenId.index'
import { Route as AppAgenAgenIdOutletRouteImport } from './routes/_app.agen.$agenId.outlet'
import { Route as AppSalesAreaWilayahProdukRouteImport } from './routes/_app.sales-area.$wilayah.$produk'
import { Route as AppTsoTsoIdIndexRouteImport } from './routes/_app.tso.$tsoId.index'
import { Route as AppTsoTsoIdEditRouteImport } from './routes/_app.tso.$tsoId.edit'
import { Route as AppWilayahWilayahAgenRouteImport } from './routes/_app.wilayah.$wilayah.agen'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGudangWilayahRoute = AppGudangWilayahRouteImport.update({
  id: '/gudang-wilayah',
  path: '/gudang-wilayah',
  getParentRoute: () => AppRoute,
} as any)
const AppMitraRoute = AppMitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => AppRoute,
} as any)
const AppTsoRoute = AppTsoRouteImport.update({
  id: '/tso',
  path: '/tso',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenAgenIdRoute = AppAgenAgenIdRouteImport.update({
  id: '/agen/$agenId',
  path: '/agen/$agenId',
  getParentRoute: () => AppRoute,
} as any)
const AppOutletOutletIdRoute = AppOutletOutletIdRouteImport.update({
  id: '/outlet/$outletId',
  path: '/outlet/$outletId',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesAreaRegisterRoute = AppSalesAreaRegisterRouteImport.update({
  id: '/sales-area/register',
  path: '/sales-area/register',
  getParentRoute: () => AppRoute,
} as any)
const AppTsoIndexRoute = AppTsoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTsoRoute,
} as any)
const AppTsoTsoIdRoute = AppTsoTsoIdRouteImport.update({
  id: '/$tsoId',
  path: '/$tsoId',
  getParentRoute: () => AppTsoRoute,
} as any)
const AppTsoCreateRoute = AppTsoCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppTsoRoute,
} as any)
const AppAgenAgenIdIndexRoute = AppAgenAgenIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgenAgenIdRoute,
} as any)
const AppAgenAgenIdOutletRoute = AppAgenAgenIdOutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => AppAgenAgenIdRoute,
} as any)
const AppSalesAreaWilayahProdukRoute =
  AppSalesAreaWilayahProdukRouteImport.update({
    id: '/sales-area/$wilayah/$produk',
    path: '/sales-area/$wilayah/$produk',
    getParentRoute: () => AppRoute,
  } as any)
const AppTsoTsoIdIndexRoute = AppTsoTsoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTsoTsoIdRoute,
} as any)
const AppTsoTsoIdEditRoute = AppTsoTsoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppTsoTsoIdRoute,
} as any)
const AppWilayahWilayahAgenRoute = AppWilayahWilayahAgenRouteImport.update({
  id: '/wilayah/$wilayah/agen',
  path: '/wilayah/$wilayah/agen',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/gudang-wilayah': typeof AppGudangWilayahRoute
  '/mitra': typeof AppMitraRoute
  '/tso': typeof AppTsoRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/agen/$agenId': typeof AppAgenAgenIdRouteWithChildren
  '/outlet/$outletId': typeof AppOutletOutletIdRoute
  '/sales-area/register': typeof AppSalesAreaRegisterRoute
  '/tso/$tsoId': typeof AppTsoTsoIdRouteWithChildren
  '/tso/create': typeof AppTsoCreateRoute
  '/tso/': typeof AppTsoIndexRoute
  '/agen/$agenId/outlet': typeof AppAgenAgenIdOutletRoute
  '/sales-area/$wilayah/$produk': typeof AppSalesAreaWilayahProdukRoute
  '/tso/$tsoId/edit': typeof AppTsoTsoIdEditRoute
  '/wilayah/$wilayah/agen': typeof AppWilayahWilayahAgenRoute
  '/agen/$agenId/': typeof AppAgenAgenIdIndexRoute
  '/tso/$tsoId/': typeof AppTsoTsoIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/gudang-wilayah': typeof AppGudangWilayahRoute
  '/mitra': typeof AppMitraRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/outlet/$outletId': typeof AppOutletOutletIdRoute
  '/sales-area/register': typeof AppSalesAreaRegisterRoute
  '/tso/create': typeof AppTsoCreateRoute
  '/tso': typeof AppTsoIndexRoute
  '/agen/$agenId/outlet': typeof AppAgenAgenIdOutletRoute
  '/sales-area/$wilayah/$produk': typeof AppSalesAreaWilayahProdukRoute
  '/tso/$tsoId/edit': typeof AppTsoTsoIdEditRoute
  '/wilayah/$wilayah/agen': typeof AppWilayahWilayahAgenRoute
  '/agen/$agenId': typeof AppAgenAgenIdIndexRoute
  '/tso/$tsoId': typeof AppTsoTsoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/gudang-wilayah': typeof AppGudangWilayahRoute
  '/_app/mitra': typeof AppMitraRoute
  '/_app/tso': typeof AppTsoRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/agen/$agenId': typeof AppAgenAgenIdRouteWithChildren
  '/_app/outlet/$outletId': typeof AppOutletOutletIdRoute
  '/_app/sales-area/register': typeof AppSalesAreaRegisterRoute
  '/_app/tso/$tsoId': typeof AppTsoTsoIdRouteWithChildren
  '/_app/tso/create': typeof AppTsoCreateRoute
  '/_app/tso/': typeof AppTsoIndexRoute
  '/_app/agen/$agenId/outlet': typeof AppAgenAgenIdOutletRoute
  '/_app/sales-area/$wilayah/$produk': typeof AppSalesAreaWilayahProdukRoute
  '/_app/tso/$tsoId/edit': typeof AppTsoTsoIdEditRoute
  '/_app/wilayah/$wilayah/agen': typeof AppWilayahWilayahAgenRoute
  '/_app/agen/$agenId/': typeof AppAgenAgenIdIndexRoute
  '/_app/tso/$tsoId/': typeof AppTsoTsoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/gudang-wilayah'
    | '/mitra'
    | '/tso'
    | '/admin/users'
    | '/agen/$agenId'
    | '/outlet/$outletId'
    | '/sales-area/register'
    | '/tso/$tsoId'
    | '/tso/create'
    | '/tso/'
    | '/agen/$agenId/outlet'
    | '/sales-area/$wilayah/$produk'
    | '/tso/$tsoId/edit'
    | '/wilayah/$wilayah/agen'
    | '/agen/$agenId/'
    | '/tso/$tsoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/gudang-wilayah'
    | '/mitra'
    | '/'
    | '/admin/users'
    | '/outlet/$outletId'
    | '/sales-area/register'
    | '/tso/create'
    | '/tso'
    | '/agen/$agenId/outlet'
    | '/sales-area/$wilayah/$produk'
    | '/tso/$tsoId/edit'
    | '/wilayah/$wilayah/agen'
    | '/agen/$agenId'
    | '/tso/$tsoId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/gudang-wilayah'
    | '/_app/mitra'
    | '/_app/tso'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/agen/$agenId'
    | '/_app/outlet/$outletId'
    | '/_app/sales-area/register'
    | '/_app/tso/$tsoId'
    | '/_app/tso/create'
    | '/_app/tso/'
    | '/_app/agen/$agenId/outlet'
    | '/_app/sales-area/$wilayah/$produk'
    | '/_app/tso/$tsoId/edit'
    | '/_app/wilayah/$wilayah/agen'
    | '/_app/agen/$agenId/'
    | '/_app/tso/$tsoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gudang-wilayah': {
      id: '/_app/gudang-wilayah'
      path: '/gudang-wilayah'
      fullPath: '/gudang-wilayah'
      preLoaderRoute: typeof AppGudangWilayahRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mitra': {
      id: '/_app/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof AppMitraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tso': {
      id: '/_app/tso'
      path: '/tso'
      fullPath: '/tso'
      preLoaderRoute: typeof AppTsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agen/$agenId': {
      id: '/_app/agen/$agenId'
      path: '/agen/$agenId'
      fullPath: '/agen/$agenId'
      preLoaderRoute: typeof AppAgenAgenIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outlet/$outletId': {
      id: '/_app/outlet/$outletId'
      path: '/outlet/$outletId'
      fullPath: '/outlet/$outletId'
      preLoaderRoute: typeof AppOutletOutletIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-area/register': {
      id: '/_app/sales-area/register'
      path: '/sales-area/register'
      fullPath: '/sales-area/register'
      preLoaderRoute: typeof AppSalesAreaRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tso/': {
      id: '/_app/tso/'
      path: '/'
      fullPath: '/tso/'
      preLoaderRoute: typeof AppTsoIndexRouteImport
      parentRoute: typeof AppTsoRoute
    }
    '/_app/tso/$tsoId': {
      id: '/_app/tso/$tsoId'
      path: '/$tsoId'
      fullPath: '/tso/$tsoId'
      preLoaderRoute: typeof AppTsoTsoIdRouteImport
      parentRoute: typeof AppTsoRoute
    }
    '/_app/tso/create': {
      id: '/_app/tso/create'
      path: '/create'
      fullPath: '/tso/create'
      preLoaderRoute: typeof AppTsoCreateRouteImport
      parentRoute: typeof AppTsoRoute
    }
    '/_app/agen/$agenId/': {
      id: '/_app/agen/$agenId/'
      path: '/'
      fullPath: '/agen/$agenId/'
      preLoaderRoute: typeof AppAgenAgenIdIndexRouteImport
      parentRoute: typeof AppAgenAgenIdRoute
    }
    '/_app/agen/$agenId/outlet': {
      id: '/_app/agen/$agenId/outlet'
      path: '/outlet'
      fullPath: '/agen/$agenId/outlet'
      preLoaderRoute: typeof AppAgenAgenIdOutletRouteImport
      parentRoute: typeof AppAgenAgenIdRoute
    }
    '/_app/sales-area/$wilayah/$produk': {
      id: '/_app/sales-area/$wilayah/$produk'
      path: '/sales-area/$wilayah/$produk'
      fullPath: '/sales-area/$wilayah/$produk'
      preLoaderRoute: typeof AppSalesAreaWilayahProdukRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tso/$tsoId/': {
      id: '/_app/tso/$tsoId/'
      path: '/'
      fullPath: '/tso/$tsoId/'
      preLoaderRoute: typeof AppTsoTsoIdIndexRouteImport
      parentRoute: typeof AppTsoTsoIdRoute
    }
    '/_app/tso/$tsoId/edit': {
      id: '/_app/tso/$tsoId/edit'
      path: '/edit'
      fullPath: '/tso/$tsoId/edit'
      preLoaderRoute: typeof AppTsoTsoIdEditRouteImport
      parentRoute: typeof AppTsoTsoIdRoute
    }
    '/_app/wilayah/$wilayah/agen': {
      id: '/_app/wilayah/$wilayah/agen'
      path: '/wilayah/$wilayah/agen'
      fullPath: '/wilayah/$wilayah/agen'
      preLoaderRoute: typeof AppWilayahWilayahAgenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTsoTsoIdRouteChildren {
  AppTsoTsoIdEditRoute: typeof AppTsoTsoIdEditRoute
  AppTsoTsoIdIndexRoute: typeof AppTsoTsoIdIndexRoute
}

const AppTsoTsoIdRouteChildren: AppTsoTsoIdRouteChildren = {
  AppTsoTsoIdEditRoute: AppTsoTsoIdEditRoute,
  AppTsoTsoIdIndexRoute: AppTsoTsoIdIndexRoute,
}

const AppTsoTsoIdRouteWithChildren = AppTsoTsoIdRoute._addFileChildren(
  AppTsoTsoIdRouteChildren,
)

interface AppTsoRouteChildren {
  AppTsoTsoIdRoute: typeof AppTsoTsoIdRouteWithChildren
  AppTsoCreateRoute: typeof AppTsoCreateRoute
  AppTsoIndexRoute: typeof AppTsoIndexRoute
}

const AppTsoRouteChildren: AppTsoRouteChildren = {
  AppTsoTsoIdRoute: AppTsoTsoIdRouteWithChildren,
  AppTsoCreateRoute: AppTsoCreateRoute,
  AppTsoIndexRoute: AppTsoIndexRoute,
}

const AppTsoRouteWithChildren =
  AppTsoRoute._addFileChildren(AppTsoRouteChildren)

interface AppAgenAgenIdRouteChildren {
  AppAgenAgenIdOutletRoute: typeof AppAgenAgenIdOutletRoute
  AppAgenAgenIdIndexRoute: typeof AppAgenAgenIdIndexRoute
}

const AppAgenAgenIdRouteChildren: AppAgenAgenIdRouteChildren = {
  AppAgenAgenIdOutletRoute: AppAgenAgenIdOutletRoute,
  AppAgenAgenIdIndexRoute: AppAgenAgenIdIndexRoute,
}

const AppAgenAgenIdRouteWithChildren = AppAgenAgenIdRoute._addFileChildren(
  AppAgenAgenIdRouteChildren,
)

interface AppRouteChildren {
  AppGudangWilayahRoute: typeof AppGudangWilayahRoute
  AppMitraRoute: typeof AppMitraRoute
  AppTsoRoute: typeof AppTsoRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAgenAgenIdRoute: typeof AppAgenAgenIdRouteWithChildren
  AppOutletOutletIdRoute: typeof AppOutletOutletIdRoute
  AppSalesAreaRegisterRoute: typeof AppSalesAreaRegisterRoute
  AppSalesAreaWilayahProdukRoute: typeof AppSalesAreaWilayahProdukRoute
  AppWilayahWilayahAgenRoute: typeof AppWilayahWilayahAgenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGudangWilayahRoute: AppGudangWilayahRoute,
  AppMitraRoute: AppMitraRoute,
  AppTsoRoute: AppTsoRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAgenAgenIdRoute: AppAgenAgenIdRouteWithChildren,
  AppOutletOutletIdRoute: AppOutletOutletIdRoute,
  AppSalesAreaRegisterRoute: AppSalesAreaRegisterRoute,
  AppSalesAreaWilayahProdukRoute: AppSalesAreaWilayahProdukRoute,
  AppWilayahWilayahAgenRoute: AppWilayahWilayahAgenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
